"use client";
import { Box, Flex, Text } from "@chakra-ui/react";
import React from "react";

export default function Tnc() {
  return (
    <Box padding={{ base: "15px", md: "30px", lg: "70px" }}>
      <Text fontSize="1.7rem" mb={10}>
        Terms and conditions
      </Text>
      <Flex direction="column" gap={5}>
        <Text fontSize="1.2rem">{"Acceptance of Terms:"}</Text>
        {
          'By using thifood.com ("the Site") and its online services provided by The Honest Ingredients Private Ltd. ("THI," "we," or "us"), you acknowledge and agree to the terms outlined in this Agreement. Whether or not you are a registered user, accessing or using the Service indicates your acceptance of these Terms of Use. '
        }
        <Text fontSize="1.2rem">{"Electronic Record:"}</Text>
        {
          "This document serves as an electronic record in accordance with the Information Technology Act, 2000. It is generated by a computer system and complies with the rules and regulations outlined in the Information Technology (Intermediaries guidelines) Rules, 2011."
        }
        <Text fontSize="1.2rem">{"Legal Eligibility:"}</Text>
        {
          'Use of the Site is restricted to individuals who can form legally binding contracts under applicable law. Persons considered "incompetent to contract" under the Indian Contract Act, 1872, including un-discharged insolvents, are ineligible. Minors under 18 may use the Site under the supervision of a parent or legal guardian. '
        }
        <Text fontSize="1.2rem">{"Age Restrictions:"}</Text>
        {
          "If you are under 13, refrain from attempting to register for the Service or provide personal information. If we discover personal information collected from anyone under 13 without parental consent, we will promptly delete it. Account Creation: To make a purchase on the Site, you must create an account. This account allows easy access to order history and prints. Ensure that the information provided is accurate and updated."
        }{" "}
        <br />
        <br />
        {
          "By continuing to use thifood.com, you acknowledge that the exclusions and limitations of liability outlined in this Agreement are reasonable. These terms are subject to change, and it is your responsibility to review them periodically for updates. Your ongoing use of the Service signifies your acceptance of any modifications to these Terms of Use."
        }
      </Flex>
    </Box>
  );
}
